### PR TITLE
Fix timestamps not used when signing payload

### LINKED ISSUE #228: Timestamps are not signed with post processed data
One of the reasons for moving from preprocessingV1 to V2 was to be able to modify the responses. Currently Airnode Feed doesn't mimic airnode behavior seen here: https://github.com/api3dao/airnode/blob/ea29aefb12e75d919ebf4bca1e53673baa72c4d5/packages/airnode-node/src/api/index.ts#L277

### PR DESCRIPTION
**Pull request by aquarat**
Timestamps returned from post-processing V2 were being discarded. 
This follows the behaviour of Airnode in that if a post-processing-supplied timestamp is available, it will be used, otherwise it will fall back to the system clock.

Closes #228 

@Ashar2shahid, can you test this branch? You can do so by cloning it and building the docker images locally (`pnpm docker:build`)

### CODE REVIEW

**Comment by bbenligiray** [comment]
@dcroote can you check out if this behaves the same as Airnode?

**Comment by Ashar2shahid** [comment]
a little hard for me to test this since I don't have a config at hand, Ill review the code and let someone who has a working config test it (or if I can get a config I can test it)

**Comment by aquarat** [comment]
> a little hard for me to test this since I don't have a config at hand, Ill review the code and let someone who has a working config test it (or if I can get a config I can test it)

ah ok, I assumed you had found the bug as a result of testing it with some config.

File: packages/airnode-feed/src/sign-template-data.ts [hunk 1]
```diff
@@ -9,14 +9,16 @@ import type { SignedData, TemplateId } from './validation/schema';
 
 export type SignedResponse = [TemplateId, SignedData];
 
-export type TemplateResponse = [TemplateId, ExtractedAndEncodedResponse];
+export type TemplateResponse = [TemplateId, { timestamp: string; encodedResponse: ExtractedAndEncodedResponse }];
```
Comment (dcroote) [inline packages/airnode-feed/src/sign-template-data.ts:12]: Not knowing enough about consumers of these responses- I presume it's OK that the field structure of the `TemplateResponse` type has changed given the `SignedResponse` type is unchanged and it is the data type that is [ultimately stored](https://github.com/api3dao/signed-api/blob/5590378a85fdb695e841794cbeeebe4b76b6bba8/packages/airnode-feed/src/fetch-beacon-data.ts#L28-L30)?

**Review by dcroote — COMMENTED** [review]
Yes, it looks the same in that now post-processing timestamps are retained [equivalently to Airnode](
https://github.com/api3dao/airnode/blob/ea29aefb12e75d919ebf4bca1e53673baa72c4d5/packages/airnode-node/src/api/index.ts#L276-L277) during response extraction and encoding. I added a couple of other minor comments.

File: packages/airnode-feed/src/sign-template-data.ts (hunk 1 above)
Comment (aquarat) [reply packages/airnode-feed/src/sign-template-data.ts:12]: Thanks for the comments Derek.

The type is used internally and the TS compiler would exit in error if the consumers were unhappy 🤷 , so I figured this was fine :). Regardless, the type now represents the actual data I think.

File: packages/e2e/README.md [hunk 2]
```diff
@@ -4,9 +4,10 @@
 
 ## Getting started
 
-1. Copy the Airnode feed secrets. Run `cp airnode-feed/secrets.example.env airnode-feed/secrets.env`. If you are using
-   Docker Desktop, you need to change the URL in `airnode-feed/secrets.env` from `localhost` to `host.docker.internal`,
-   because Airnode feed is running inside a Docker container.
+1. Copy the Airnode feed secrets. Whilst inside `src` run
```
[the remark this answers is not in the document]
Comment (aquarat) [reply packages/e2e/README.md:7]: True true, I'll amend this. I found the issue while working through these instructions for testing purposes. :)

File: packages/airnode-feed/src/sign-template-data.ts (hunk 1 above)
Comment (dcroote) [reply packages/airnode-feed/src/sign-template-data.ts:12]: Sorry for being confusing- I meant I didn't know if there were *external* consumers, otherwise agree

File: packages/e2e/README.md [hunk 3]
```diff
@@ -4,10 +4,11 @@
...
 
-1. Copy the Airnode feed secrets. Run `cp airnode-feed/secrets.example.env airnode-feed/secrets.env`. If you are using
-   Docker Desktop, you need to change the URL in `airnode-feed/secrets.env` from `localhost` to `host.docker.internal`,
-   because Airnode feed is running inside a Docker container.
-2. Copy the Signed API secrets. Run `cp signed-api/secrets.example.env signed-api/secrets.env`
+1. Copy the Airnode feed secrets. Whilst inside `src` run
+   `cp airnode-feed/secrets.example.env airnode-feed/secrets.env`. If you are using Docker Desktop, you need to change
+   the URL in `airnode-feed/secrets.env` from `localhost` to `host.docker.internal`, because Airnode feed is running
+   inside a Docker container.
+2. Copy the Signed API secrets. Whilst inside `src` run run `cp signed-api/secrets.example.env signed-api/secrets.env`
```
Comment (dcroote) [inline packages/e2e/README.md:11]: "run run" 😅

**Review by dcroote — APPROVED** [review]

File: packages/e2e/README.md (hunk 3 above)
Comment (aquarat) [reply packages/e2e/README.md:11]: 🙈 sorry! thanks for catching that, I really had too look for it 😆

File: packages/e2e/README.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (Siegrift) [reply packages/e2e/README.md:7]: Thanks for catching this.

**Comment by Siegrift** [comment]
👍 LGTM
